apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-nginx
  labels:
    app: rs
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template: 
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
     containers:
       - name: nginx-container
         image: nginx:1.18

