apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: math-add-job
spec:
  parallelism: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ubuntu
        name: math-add-job
        command: ["expr","3","+","2"]
      restartPolicy: Never
