apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  containers:
  - image: kodekloud/event-simulator
    name: app
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  - image: kodekloud/filebeat-configured
    name: sidecar
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/event-simulator
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log/webapp
      type: DirectoryOrCreate
