apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-using-node-selector
  labels:
    app: nginx-app
spec:
  containers:
   - name: nginx-container
     image: nginx
  nodeSelector:
    server: web-server-node
