apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-using-service-account
  labels:
    app: nginx-app
spec:
  securityContext:
    runAsUser: 1000
  containers:
   - name: nginx-container
     image: nginx
  serviceAccount: app-service-account
