apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-using-config-map
  labels:
    app: nginx-app
spec:
  containers:
   - name: nginx-container
     image: nginx
     envFrom:
     - configMapRef:
        name: app-config
