apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    app: rc
spec:
  replicas: 3
  template: 
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
     containers:
       - name: nginx-container
         image: nginx
