apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-03-02T11:47:15Z"
  labels:
    run: gop-fileserver
  name: gop-fileserver
  namespace: default
  resourceVersion: "4138"
  selfLink: /api/v1/namespaces/default/pods/gop-fileserver
  uid: 090c2150-7b4d-11eb-a41b-0242ac11000a
spec:
  containers:
  - image: kodekloud/fileserver
    imagePullPolicy: Always
    name: gop-fileserver
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-qj5tz
      readOnly: true
    - mountPath: /web
      name: data-store
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
  - name: default-token-qj5tz
    secret:
      defaultMode: 420
      secretName: default-token-qj5tz
status:
  phase: Pending
  qosClass: BestEffort