apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    run: gop-fileserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31200